name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Download Test Runner
        run: |
          docker pull tarnadas/near-sandbox

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Tests
        run: |
          ./run-tests.sh
